# Generated by Django 5.2.7 on 2025-11-10 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('last_name', models.CharField()),
                ('year_of_birth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('synopsis', models.TextField(max_length=1000)),
                ('genre', models.CharField(choices=[('AC', 'Action'), ('DR', 'Drama'), ('CO', 'Comedy'), ('SF', 'Sci-Fi'), ('HO', 'Horror')], max_length=2)),
                ('director', models.CharField(max_length=100)),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)])),
                ('release_date', models.DateField()),
                ('announcement_date', models.DateField()),
                ('has_subtitles', models.BooleanField()),
                ('subtitles_language', models.CharField(blank=True)),
                ('imdb', models.URLField(blank=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('actors', models.ManyToManyField(blank=True, to='cinemaapp.actor')),
            ],
        ),
    ]
