# Generated by Django 5.2.7 on 2025-10-27 13:39

import mascotaapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, validators=[mascotaapp.models.valida_peso])),
                ('vacunado', models.BooleanField()),
                ('ultima_vacuna', models.DateField(blank=True, null=True)),
                ('email_duenyo', models.EmailField(blank=True, max_length=254)),
                ('domicilio_duenyo', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
