# Generated by Django 5.2.7 on 2025-11-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duenyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('apellidos', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.FileField(default='nada', upload_to='fotitos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('GA', 'Gato'), ('PE', 'Perro'), ('CA', 'Canario'), ('CO', 'Conejo'), ('TO', 'Tortuga')], default='GA', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mascota',
            name='duenyos',
            field=models.ManyToManyField(to='mascotaapp.duenyo'),
        ),
    ]
