# Generated by Django 5.2.7 on 2025-11-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotaapp', '0002_duenyo_mascota_foto_mascota_tipo_mascota_duenyos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='duenyos',
            field=models.ManyToManyField(blank=True, to='mascotaapp.duenyo'),
        ),
    ]
