# Generated by Django 5.2.8 on 2025-11-24 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animatronic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('animal', models.CharField(choices=[('BE', 'Bear'), ('CH', 'Chicken'), ('BU', 'Bunny'), ('FO', 'Fox')], max_length=2)),
                ('build_date', models.DateField()),
                ('decommissioned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attendants', models.IntegerField()),
                ('animatronic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='freddyapp.animatronic')),
            ],
        ),
    ]
