# Generated by Django 5.2.8 on 2025-11-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freddyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='animatronic',
        ),
        migrations.AddField(
            model_name='animatronic',
            name='parties',
            field=models.ManyToManyField(blank=True, to='freddyapp.party'),
        ),
    ]
