# Generated by Django 5.2.7 on 2025-10-20 12:30

import django.core.validators
import hospitalapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('apellidos_paciente', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('dni', models.CharField(max_length=9, validators=[django.core.validators.MinLengthValidator(9)])),
                ('fecha_cita', models.DateField()),
                ('hora_cita', models.DateTimeField()),
                ('medicacion', models.BooleanField()),
                ('medicamento', models.CharField()),
                ('dosis', models.IntegerField(validators=[hospitalapp.models.valida_tres, hospitalapp.models.valida_dosis])),
            ],
        ),
    ]
