# Generated by Django 5.2.7 on 2025-10-21 12:14

import hospitalapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_alter_registro_dosis_alter_registro_hora_cita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='dosis',
            field=models.IntegerField(blank=True, help_text='Opcional: indica la dosis si procede', validators=[hospitalapp.models.valida_tres, hospitalapp.models.valida_dosis]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='medicamento',
            field=models.CharField(blank=True, help_text='Opcional: indica los medicamentos si procede'),
        ),
    ]
