# Generated by Django 5.2.7 on 2025-10-21 12:24

import hospitalapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_alter_registro_dosis_alter_registro_medicamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='dosis',
            field=models.IntegerField(blank=True, null=True, validators=[hospitalapp.models.valida_tres, hospitalapp.models.valida_dosis]),
        ),
    ]
