# Generated by Django 5.2.7 on 2025-10-22 11:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0005_alter_registro_dosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='proxima_cita',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
