# Generated by Django 5.2.7 on 2025-10-20 11:17

import hotelapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_alter_checkin_dni_alter_checkin_ncliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='numclientes',
            field=models.IntegerField(default=0, validators=[hotelapp.models.valida_par]),
            preserve_default=False,
        ),
    ]
