# Generated by Django 5.2.7 on 2025-10-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhotel', models.CharField(max_length=100)),
                ('ncliente', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=9)),
                ('fechaentrada', models.DateField()),
                ('fechasalida', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
