# Generated by Django 5.2.7 on 2025-10-27 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('raza', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(0.01), django.core.validators.MinValueValidator(200.0)])),
                ('vacunado', models.BooleanField()),
                ('ultima_vacuna', models.DateField()),
                ('email_duenyo', models.EmailField(blank=True, max_length=254)),
                ('domicilio_duenyo', models.TextField(blank=True, max_length=100)),
            ],
        ),
    ]
