# Generated by Django 5.2.7 on 2025-10-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotaapp', '0002_alter_mascota_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='ultima_vacuna',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='vacunado',
            field=models.BooleanField(default=False),
        ),
    ]
