# Generated by Django 5.2.7 on 2025-10-27 12:08

import mascotaapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotaapp', '0003_alter_mascota_ultima_vacuna_alter_mascota_vacunado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[mascotaapp.models.comprobar_peso]),
        ),
    ]
