# Generated by Django 5.2.7 on 2025-11-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotaapp', '0004_alter_mascota_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duenyos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('apellidos', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='foto',
            field=models.FileField(default='nada', upload_to='foto/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('GT', 'Gato'), ('PR', 'Perro'), ('CAN', 'Canario'), ('CON', 'Conejo'), ('TOR', 'Tortuga')], default='nada'),
            preserve_default=False,
        ),
    ]
