# Generated by Django 5.2.7 on 2025-11-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotaapp', '0005_duenyos_mascota_foto_mascota_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.FileField(blank=True, upload_to='foto/'),
        ),
    ]
