# Generated by Django 5.2.7 on 2025-11-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotaapp', '0006_alter_mascota_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.FileField(upload_to='foto/'),
        ),
    ]
