# Generated by Django 5.2.7 on 2025-11-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotaapp', '0007_alter_mascota_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='duenyos',
            field=models.ManyToManyField(to='mascotaapp.duenyos'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('GT', 'Gato'), ('PR', 'Perro'), ('CAN', 'Canario'), ('CON', 'Conejo'), ('TOR', 'Tortuga')], max_length=3),
        ),
    ]
