# Generated by Django 5.2.7 on 2025-10-22 12:30

import videojuegoapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_juego', models.CharField(max_length=50)),
                ('plataforma', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=2000)),
                ('url', models.URLField()),
                ('fecha_anuncio', models.DateField()),
                ('fecha_lanzamiento', models.DateField()),
                ('pegi', models.IntegerField(validators=[videojuegoapp.models.valida_pegi])),
                ('online', models.BooleanField()),
                ('precio_salida', models.DecimalField(decimal_places=2, max_digits=2)),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
