# Generated by Django 5.2.7 on 2025-10-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='precio_actual',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='registro',
            name='precio_salida',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
