# Generated by Django 5.2.7 on 2025-10-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegoapp', '0002_alter_registro_precio_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='descripcion',
            field=models.TextField(max_length=2000),
        ),
    ]
